### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Suspense4615** [Suggester/Documentation#138]
# To Do
### FAQ
Troubleshoot for common issues:
 - [x] config errors
 - [x] very basic elements 
 - [x] right to data deletion 

### New Pages
- [ ] Credits page
- [x] Requested Permissions Explainer
- [ ] Better `.search` docs 

### In-depth guides:
- [x] Managing suggestions
- [x] Handling Modes
- [x] Optional but recommended elements (recommended config)

### Other
- [x] Actual background
- [x] List commands available in DMs
